### ISSUE TITLE
Convert Cerberus Objects + Keymaster Npc

### ISSUE THREAD

**Issue by JonathanSirens** [JonathanSirens/Runique-Source#26]
There is a npc + dialog for a npc called keymaster that is supposed to be in the middle of the Cerberus layer. There is a class for clicking the cerberus objects that needs to be converted over from Armadyl

**Comment by high105** [comment]
Cerberus added, Updated combat script so it no longer throws a null pointer when unregistering ghosts.
Drops need to be added
Even added Item combinations for drops
