### ISSUE TITLE
Treasure Island

### ISSUE THREAD

**Issue by JonathanSirens** [JonathanSirens/Runique-Source#31]
It is like partly added, needs to be finished

-Npc's I didn't test combat script
-Npc's dont drop keys
-Chests need to be added
-New donator feature, after treasure island monsters are killed sends key to inventory

**Comment by high105** [comment]
Updated:
Death Mob is invisible - all key models are invisible. 
Everything else works: Bosses drop keys, Chests Spawns, Keys open chest
