### ISSUE TITLE
Tormented Demons

### ISSUE THREAD

**Issue by EthannTM** [JonathanSirens/Runique-Source#49]
Alright well I wasn't going to make this issue but it's happened every time so I'm assuming it's a bug, once the NPC is hit down to what I'm assuming is 0HP I just keep hitting 0's (with 9999 strength) until I use like a dragon claw spec which also hits a 0 but then somehow gets the kill?

Needs to be looked into, only happened with Tormented Demons

Check the Gyazo:
https://gyazo.com/cafc92a7210a0f2c19e593fb7af5493e

**Comment by high105** [comment]
I believe this issue only happens with TDs due to their prayer. Has this happened with any other npcs?
